# Generated by Django 5.2.1 on 2025-06-05 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_courtcase_casedocument_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcase',
            name='case_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courtcase',
            name='client_tel',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
